{
 "title": "Minio Overview",
 "description": "Minio dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(minio_version_info,instance)"
   },
   { "name": "interval", "query": "2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Start time of the Minio server",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds)",
     "legendFormat": "Start time of the Minio servers"
    }
   ]
  },
  {
   "title": "Total disks",
   "type": "singlestat",
   "description": "Total number of disks for current MinIO server instances",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(minio_disks_total)",
     "legendFormat": "Total number of disks for current MinIO server instances"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "graph",
   "description": "Number of total/offline disks for current MinIO server instances",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_disks_offline{instance=~\"$instance\"}",
     "legendFormat": "Offline {{instance}}"
    },
    {
     "expr": "minio_disks_total{instance=~\"$instance\"}",
     "legendFormat": "Total {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "description": "Storage space usage",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "disk_storage_used{instance=~\"$instance\"}",
     "legendFormat": "used {{instance}}"
    },
    {
     "expr": "disk_storage_available{instance=~\"$instance\"}",
     "legendFormat": "available {{instance}}"
    },
    {
     "expr": "disk_storage_total{instance=~\"$instance\"}",
     "legendFormat": "total {{instance}}"
    }
   ]
  },
  {
   "title": "Offline disks",
   "type": "singlestat",
   "description": "Total number of offline disks for current MinIO server instances",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(minio_disks_offline)",
     "legendFormat": "Total number of offline disks for current MinIO server instances"
    }
   ]
  },
  {
   "title": "GO Memory Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "bytes allocated {{instance}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "alloc rate {{instance}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "stack inuse {{instance}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "heap inuse {{instance}}"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "graph",
   "description": "Total user and system CPU time spent in seconds",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Total CPU {{instance}}"
    }
   ]
  },
  {
   "title": "Data Transmitted",
   "type": "graph",
   "description": " Total In/Out Throughput",
   "gridPos": { "h": 7, "w": 25, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "-rate(internode_tx_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Sent {{instance}}"
    },
    {
     "expr": "rate(internode_rx_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Received {{instance}}"
    }
   ]
  }
 ]
}